AsyncException: use str() on the proxied exception to get the message instead of accessing self.message or self.args.  Results in simpler code that I think is more correct.
kaa.Socket changes: new buffer_size and chunk_size properties; custom __repr__
that shows fileno; use kaa.tempfile() on unix sockets if only filename is
specified; clear out stale unix sockets when listening (this logic moved from
kaa.rpc); register shutdown handler to close socket and clean up.

kaa.rpc: significantly refactored to use kaa.Socket; new Channel.close() method
added.



git-svn-id: svn://svn.freevo.org/kaa/trunk/base@3173 a8f5125c-1e01-0410-8897-facf34644b8e